// Generated by CoffeeScript 1.6.2
var root;

root = typeof exports !== "undefined" && exports !== null ? exports : this;

root.fn = function(ua) {
  ua.then("переход на страницу программ", function() {
    var _this = this;
    this.cleanup();
    this.click("[href='#show']");
    return this.wait("li[name='page']", function(selector) {
      return _this.innerText(selector) === "1 / 2";
    });
  });
  ua.then("проматываем на одну страницу вперед", function() {
    var _this = this;
    this.click_jq("li[name='forward']");
    return this.wait("li[name='page']", function(selector) {
      return _this.innerText(selector) === "2 / 2";
    });
  });
  ua.then("переход на страницу событий", function() {
    var _this = this;
    this.click("[href='#event']");
    this.state = "event page";
    return this.wait("li[name='page']", function(selector) {
      return _this.innerText(selector) === "1 / 1";
    });
  });
  ua.then("переход на страницу программ со страницы событий", function() {
    var _this = this;
    this.click("[href='#show']");
    this.state = "show page";
    return this.wait("li[name='page']", function(selector) {
      return _this.innerText(selector) === "2 / 2";
    });
  });
  ua.then("клик по кнопке добавить", function() {
    this.click("[pi='Create']");
    return this.wait(".cke_wysiwyg_frame");
  });
  ua.then("возврат со страницы добавления программы", function() {
    var _this = this;
    this.page.goBack();
    return this.wait("li[name='page']", function(selector) {
      return _this.innerText(selector) === "2 / 2";
    });
  });
  ua.then("конец теста", function() {
    return this.exit();
  });
  return ua;
};
