// Generated by CoffeeScript 1.6.2
var UA,
  __slice = [].slice;

UA = (function() {
  UA.prototype.page = null;

  UA.prototype.state = "init";

  UA.prototype.rules = null;

  UA.prototype.retryTimeout = 100;

  UA.prototype.waitTimeout = 5000;

  function UA() {
    var _this = this;
    this.rules = {};
    this.page = require("webpage").create();
    this.page.onResourceRequested = function(r) {
      return console.log("request() " + r.url);
    };
    this.page.onLoadFinished = function(r) {
      return _this.run("page/finish");
    };
    this.tr("init", "page/open", "page/requested", function(uri) {
      var _this = this;
      return this.page.open(uri, function(status) {
        return _this.run("page/open", status);
      });
    });
    this.page.onConsoleMessage = function(msg) {
      return console.log("CONSOLE: " + msg);
    };
    this.page.onError = function(msg) {
      return console.log("ERROR: " + msg);
    };
  }

  UA.prototype.tr = function(state, ev, newstate, fn) {
    if (!this.rules[state]) {
      this.rules[state] = {};
    }
    return this.rules[state][ev] = {
      fn: fn,
      newstate: newstate
    };
  };

  UA.prototype.run = function() {
    var args, ev, tr;
    ev = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    console.log("run() " + this.state + " -> " + ev);
    if (!this.rules[this.state]) {
      return console.log("No rules for state " + this.state);
    }
    if (!this.rules[this.state][ev]) {
      return console.log("No event " + ev + " on state " + this.state);
    }
    tr = this.rules[this.state][ev];
    if (!tr) {
      return;
    }
    this.state = tr.newstate;
    if (tr.fn) {
      return tr.fn.call(this, args);
    }
  };

  UA.prototype.jQuery = function(selector, fn) {
    return this.page.evaluate((function(selector, fn) {
      return fn.call($(selector));
    }), selector, fn);
  };

  UA.prototype.box = function(selector) {
    return this.jQuery(selector, function() {
      return {
        x: this.offset().left,
        y: this.offset().top,
        w: this.width(),
        h: this.height()
      };
    });
  };

  UA.prototype.click = function(selector) {
    var box;
    box = this.box(selector);
    return this.page.sendEvent("click", box.x + box.w / 2, box.y + box.h / 2);
  };

  UA.prototype.text = function(selector, text) {
    this.click(selector);
    return this.page.sendEvent("keypress", text);
  };

  UA.prototype.wait = function(selector, ev) {
    var handler, start,
      _this = this;
    start = new Date().getTime();
    return handler = setInterval((function() {
      var status;
      status = _this.jQuery(selector, function() {
        return this.length > 0;
      });
      if (status) {
        clearInterval(handler);
        _this.run(ev);
      }
      if (new Date().getTime() - start > _this.waitTimeout) {
        clearInterval(handler);
        return _this.run("timeout");
      }
    }), this.retryTimeout);
  };

  return UA;

})();
